### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/aws-cfn-lint-visual-studio-code#109]
We should update https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/master/CHANGELOG.md, because 1) it's visible [in the VS marketplace](https://marketplace.visualstudio.com/items/kddejong.vscode-cfn-lint/changelog), and 2) people like seeing what changed between versions (at least I do)

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/111
