### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/aws-cfn-lint-visual-studio-code#110]
![image](https://user-images.githubusercontent.com/5374887/84557976-30d4e100-ace4-11ea-9afe-6bc823665bb7.png)
![image](https://user-images.githubusercontent.com/5374887/84557982-39c5b280-ace4-11ea-98d5-ece1c714d0c5.png)
![image](https://user-images.githubusercontent.com/5374887/84557993-434f1a80-ace4-11ea-9b52-d05052c22ac8.png)
![image](https://user-images.githubusercontent.com/5374887/84557994-4944fb80-ace4-11ea-8014-267bff3c5ca7.png)

@kddejong pleaseeee document the release process somewhere

**Comment by miparnisari** [comment]
Also, we shouldn't have releases if there weren't changes for customers.

![image](https://user-images.githubusercontent.com/5374887/84558052-b6589100-ace4-11ea-985d-021fcd0df615.png)

**Comment by kddejong** [comment]
Agreed. Usually it’s because of an issue during the publish.  The publish command tags the repo, creates a commit, and changes a file. It does this first but if a later step fails it doesn’t undo it.
