### ISSUE TITLE
Include VSIX with releases

### ISSUE THREAD

**Issue by br3ndonland** [aws-cloudformation/aws-cfn-lint-visual-studio-code#113]
For flexible installation and testing of pre-releases, it would be helpful to include the [packaged VSIX extension files](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions) with each release, as they do in [aws-toolkit-vscode](https://github.com/aws/aws-toolkit-vscode/releases).

**Comment by PatMyron** [comment]
> For flexible installation

[`Download Extension` on the right panel in the Visual Studio Code marketplace](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint) should have the latest `.vsix`

> and testing of pre-releases

[Most of the recent releases have just been getting recently released AWS CloudFormation types into the Template Schema for autocompletion and documentation links](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/111/files), so we usually release without manual pre-release testing beyond the developers

Visual Studio Code does have builtin extension downgrading capability: 

<img width="510" alt="Screen Shot 2020-07-03 at 1 46 38 PM" src="https://user-images.githubusercontent.com/7014355/86496765-a35d3d80-bd33-11ea-87e1-171f7396a167.png">

but definitely let us know if you're running into any issues with new extension versions

**Comment by br3ndonland** [comment]
that works for me, thanks for clarifying
