### ISSUE TITLE
Enable in extension settings disable pydot 

### ISSUE THREAD

**Issue by polovi** [aws-cloudformation/aws-cfn-lint-visual-studio-code#117]

**Comment by PatMyron** [comment]
@polovi can you expand in more detail?

**Comment by polovi** [comment]
Seems that was some problem with VScode itself. He repeatedly trying to use pydot and show alert message that its not installed. It could be closed.

**Comment by PatMyron** [comment]
This new [template resource dependency graph preview](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/106) feature will try to use [`pydot`](https://pypi.org/project/pydot/) if the graph preview button in the top right corner is toggled on, but [`pydot`](https://pypi.org/project/pydot/) does still need to be installed separately from the [extension](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint), similarly to [`cfn-lint`](https://pypi.org/project/cfn-lint)

**Comment by rathgaurav** [comment]
I have cfn-lint and pydot installed. Yet keep getting error - [cfn-lint] 2021-06-08 13:55:44,271 - cfnlint.template - ERROR - Could not write the graph in DOT format. Please install either `pygraphviz` or `pydot` modules.

I only get this error in VS Code.

I am able to generate the .DOT file upon running the cfn-lint command with -g option from terminal.

Issue with VS code ?
