### ISSUE TITLE
how to execute linting?

### ISSUE THREAD

**Issue by DrStrangepork** [aws-cloudformation/aws-cfn-lint-visual-studio-code#134]
I've installed the latest version of this plugin, and I see nothing at all different about VSCode using CFN templates. I see the `cfnLint.*` options in my Settings but that's it. I see no new buttons, menus, menu options, linting, formatting, etc. When does linting happen? On save?

I can run a locally-installed version of `cfn-lint` (`brew install cfn-lint`), and if I run that manually, it shows me warnings and errors, but whether I configure the `cfnLint.path` in my settings to the local version or the `pip` installed version, VSCode shows nothing. I assume I am supposed to see something under Problems?

**Comment by PatMyron** [comment]
> On save? supposed to see something under `Problems`?

Should be. Something to keep in mind is that [it's trying to determine if each file is a CloudFormation template](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/99). Should see one of these messages in the `Output` tab for `.json`/`.yml`/`.yaml` files at least:

https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/a1d719d49eb67b048f0775d4b4f53424d90751e9/server/src/server.ts#L140-L158

https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/a1d719d49eb67b048f0775d4b4f53424d90751e9/server/src/server.ts#L305-L307

**Comment by DrStrangepork** [comment]
In the Output tab, after selecting "CloudFormation linter Language Server", I see this:

    Settings have been updated...
    Settings: {"cfnLint":{"enableAutocomplete":true,"validateUsingJsonSchema":true,"path":"/Users/n0304144/.pyenv/shims/cfn-lint","appendRules":[],"ignoreRules":["E1029","E2015","E3008","E3012","W1019","W2506","W2507","W3005"],"overrideSpecPath":""}}
    Determined this file is a CloudFormation Template. file:///Users/n0304144/git/SM/secrets-management-caserver/src/main/cloudformation/secrets-management-caserver.json. Found the string AWSTemplateFormatVersion
    Running... /Users/n0304144/.pyenv/shims/cfn-lint --format,json,--ignore-checks,E1029,--ignore-checks,E2015,--ignore-checks,E3008,--ignore-checks,E3012,--ignore-checks,W1019,--ignore-checks,W2506,--ignore-checks,W2507,--ignore-checks,W3005,--,"/Users/n0304144/git/SM/secrets-management-caserver/src/main/cloudformation/secrets-management-caserver.json"
    child process exited with code 0 and signal null

It appears that this is what I needed. Perhaps I was just never saving a version of my CFN that had issues, so I didn't see anything under Problems.
