### ISSUE TITLE
[cfn-lint] E3002: Invalid Property Resources/ECSService/Properties/DeploymentConfiguration/DeploymentCircuitBreaker

### ISSUE THREAD

**Issue by gvasquez95** [aws-cloudformation/aws-cfn-lint-visual-studio-code#148]
Seems like the current version of the linter does not yet support this new property for an ECS service

**Comment by kddejong** [comment]
This should be in the last few releases of [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.44.3).  What version are you using?

**Comment by gvasquez95** [comment]
v0.15.6 of this plugin according to VSCode's UI, but it makes me wonder how to know which version of `cfn-lin`t do I have installed and how to upgrade it.

**Comment by gvasquez95** [comment]
duh....pretty easy to find: `cfn-lint 0.40.0`

I'll try upgrading

**Comment by gvasquez95** [comment]
Found out the issue! `cfn-lint` was installed with `brew` in my mac, so upgrading via `pip` didn't work, and I even had to add extra Xcode tools because Python also needed a uppgrade. Now it's been upgraded to `0.44.2`, and the issue is gone. Thanks a lot!
