### ISSUE TITLE
Pydot graph render cuts off right hand side of image

### ISSUE THREAD

**Issue by Rob-El** [aws-cloudformation/aws-cfn-lint-visual-studio-code#161]
When I use the preview feature in VSCode for CloudFormation YAML files, the right side sometimes gets cut off.

![cfn-lint-render-issue-vscode](https://user-images.githubusercontent.com/58966432/110722751-b7f9ab80-81c7-11eb-90ab-e8995b386119.png)

VSCode - 1.54.1, Windows 10 64-bit, 20H2
Extension - kddejong.vscode-cfn-lint v0.16.1
cfn-lint-0.47.0
pydot-1.4.2

If I use a 3rd-party VSCode extension such as joaompinto.vscode-graphviz, it renders the full graphic.

![3rd-party-render-vscode](https://user-images.githubusercontent.com/58966432/110722748-b7611500-81c7-11eb-89b7-bc86ca082d0c.png)

Here is the graph file...
```dot
digraph "template" {
MasterDetector [label="MasterDetector\n<AWS::GuardDuty::Detector>"];
SNSNotificationTopic [label="SNSNotificationTopic\n<AWS::SNS::Topic>"];
SNSNotificationPolicy [label="SNSNotificationPolicy\n<AWS::SNS::TopicPolicy>"];
SNSNotificationSubscription [label="SNSNotificationSubscription\n<AWS::SNS::Subscription>"];
SNSInvokeLambdaPermission [label="SNSInvokeLambdaPermission\n<AWS::Lambda::Permission>"];
GuardDutyFindingEventRule [label="GuardDutyFindingEventRule\n<AWS::Events::Rule>"];
ForwardSnsNotificationLambdaRole [label="ForwardSnsNotificationLambdaRole\n<AWS::IAM::Role>"];
ForwardSnsNotification [label="ForwardSnsNotification\n<AWS::Lambda::Function>"];
ForwardSnsNotificationGroup [label="ForwardSnsNotificationGroup\n<AWS::Logs::LogGroup>"];
SNSNotificationPolicy -> SNSNotificationTopic  [key=0, label=Ref];
SNSNotificationPolicy -> SNSNotificationTopic  [key=1, label=Ref];
SNSNotificationPolicy -> SNSNotificationTopic  [key=2, label=Ref];
SNSNotificationSubscription -> SNSNotificationTopic  [key=0, label=Ref];
SNSNotificationSubscription -> ForwardSnsNotification  [key=0, label=GetAtt];
SNSInvokeLambdaPermission -> SNSNotificationTopic  [key=0, label=Ref];
SNSInvokeLambdaPermission -> ForwardSnsNotification  [key=0, label=GetAtt];
GuardDutyFindingEventRule -> SNSNotificationTopic  [key=0, label=Ref];
ForwardSnsNotification -> ForwardSnsNotificationLambdaRole  [key=0, label=GetAtt];
ForwardSnsNotificationGroup -> ForwardSnsNotification  [key=0, label=Sub];
}
```
Here is one that displays correctly:
```dot
digraph "template" {
S3KmsLoggingBucket [label="S3KmsLoggingBucket\n<AWS::S3::Bucket>"];
S3KmsBucket [label="S3KmsBucket\n<AWS::S3::Bucket>"];
S3KmsBucketPolicy [label="S3KmsBucketPolicy\n<AWS::S3::BucketPolicy>"];
S3LoggingBucket [label="S3LoggingBucket\n<AWS::S3::Bucket>"];
S3Bucket [label="S3Bucket\n<AWS::S3::Bucket>"];
S3BucketPolicy [label="S3BucketPolicy\n<AWS::S3::BucketPolicy>"];
S3KmsBucket -> S3KmsLoggingBucket  [key=0, label=Ref];
S3KmsBucketPolicy -> S3KmsBucket  [key=0, label=Ref];
S3KmsBucketPolicy -> S3KmsBucket  [key=1, label=Ref];
S3KmsBucketPolicy -> S3KmsBucket  [key=2, label=Sub];
S3Bucket -> S3LoggingBucket  [key=0, label=Ref];
S3BucketPolicy -> S3Bucket  [key=0, label=Ref];
S3BucketPolicy -> S3Bucket  [key=1, label=Ref];
S3BucketPolicy -> S3Bucket  [key=2, label=GetAtt];
S3BucketPolicy -> S3Bucket  [key=3, label=GetAtt];
S3BucketPolicy -> S3Bucket  [key=4, label=Sub];
S3BucketPolicy -> S3Bucket  [key=5, label=Sub];
S3BucketPolicy -> S3Bucket  [key=6, label=Sub];
S3BucketPolicy -> S3Bucket  [key=7, label=Sub];
S3BucketPolicy -> S3Bucket  [key=8, label=Sub];
}
```
I've tried numerous other YAML files.  All the longer ones appear to cut off.

It doesn't matter how big or small my screen is.  If I zoom out so the text is insanely tiny and then try again, the whole graphic should render completely (plenty of space in the split screen), it still cuts off at the same spot, with space on both sides of my screen.

![cfn-lint-render-issue-vscode-tiny](https://user-images.githubusercontent.com/58966432/110723548-183d1d00-81c9-11eb-86c2-8e50c0217dc6.png)

Please let me know if there's anything I should try.

Thank you!

**Comment by PatMyron** [comment]
I think this will initially depend on the relative dimensions of the graph and your editor:
https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/9a4f17e2868a5cb264dcd4c83f6980efad768e40/client/src/extension.ts#L180-L181

but you **should be able to drag and zoom around** as shown in this comment:
https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/106#issuecomment-636188312

**Comment by Rob-El** [comment]
Sorry for not responding earlier, didn't see the initial reply.

So I fiddled around, and I see that I can use the scroll on my mouse for zooming to see the whole graph.  It works, but it's very dependent on mouse position.  Very quirky, easy to loose the graph completely off-screen (zoom out/in a few times anywhere but the graph, move the mouse around a bit each time).  Dragging also works, wouldn't have thought of that.  However, "zoom out" Ctrl+- does not work.  

Is there a way to display it so that it doesn't try to cut it off on the screen width?   Is it necessary if you can scroll left/right anyways?

Also, I don't understand why scroll on my mouse works properly, but zoom out doesn't.  Is this a VSCode issue?  Many people don't have a scroll on their mouse, so I don't feel like this is a solution most people would understand.

Thanks!
