### ISSUE TITLE
Please add support for nodejs14.x to Lambda functions

### ISSUE THREAD

**Issue by gadavis2** [aws-cloudformation/aws-cfn-lint-visual-studio-code#178]
I am receiving the following notification whenever I specify nodejs14.x for my Lambda functions:

[cfn-lint] E3030: You must specify a valid value for Runtime (nodejs14.x).
Valid values are ["dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.6", "python3.7", "python3.8", "ruby2.5", "ruby2.7"]

**Comment by kddejong** [comment]
What version of `cfn-lint` are you running? 

You can try running `cfn-lint --update-specs` but depending on what version you have that may not correct issue.  This value is available in newer versions of https://github.com/aws-cloudformation/cfn-python-lint/ so you will need to upgrade your `cfn-lint` package to get rid of this error.

**Comment by PatMyron** [comment]
`pip3 install cfn-lint --upgrade`
