### ISSUE TITLE
Setup on Windows

### ISSUE THREAD

**Issue by reidca** [aws-cloudformation/aws-cfn-lint-visual-studio-code#29]
On a windows workstation with VSCode installed what are the dependencies for this?

Does cfn-lint have to be installed on Windows or can it be installed using PIP in the MINGW64 shell?

It would be useful to understand how this extension calls into cfn-lint.

**Comment by kddejong** [comment]
so I went through this morning.  It has to be installed via pip.  I installed using python though (https://www.python.org/downloads/windows/) so it was integrated with my standard powershell and my path ended up having cfn-lint available so it just worked.

**Comment by miparnisari** [comment]
Closing as this is explained [here](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code#requirements).
