### ISSUE TITLE
Add support for node10.x

### ISSUE THREAD

**Issue by DecMcLaughlin** [aws-cloudformation/aws-cfn-lint-visual-studio-code#52]
currently the linter complains with:
"message": "[cfn-lint] E3030:You must specify a valid value for Runtime (nodejs10.x).\nValid values are ['dotnetcore1.0', 'dotnetcore2.0', 'dotnetcore2.1', 'go1.x', 'java8', 'nodejs', 'nodejs4.3-edge', 'nodejs4.3', 'nodejs6.10', 'nodejs8.10', 'provided', 'python2.7', 'python3.6', 'python3.7', 'ruby2.5']",

**Comment by kddejong** [comment]
Do you know what version of cfn-lint you are using?  This should be covered with newer versions.

**Comment by DecMcLaughlin** [comment]
[cid:image001.png@01D53635.704CDDF0]

Hoi Kevin
I’m using Version 0.7.0 which appears to be the latest available via VS Code.

Thanks
Declan

**Comment by kddejong** [comment]
@DecMcLaughlin That is the version of the plugin you are using.  https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint

I'm wondering what version of cfn-lint you are using.  https://pypi.org/project/cfn-lint/
Unfortunately they are separate packages the Visual Studio Code plugin uses cfn-lint and they are managed separately so we can integrate into other IDEs and CI/CD pipelines.
