### ISSUE TITLE
Get Linter to ignore JSON files

### ISSUE THREAD

**Issue by iDVB** [aws-cloudformation/aws-cfn-lint-visual-studio-code#53]
Is there an easy way to get VSCode to ignore all JSON files for this linter? I want the default for all time to be NOT to care about JSON when looking to use this linter. We only every use YML.

**Comment by kddejong** [comment]
Let me see what I can do to help out with that.

**Comment by iDVB** [comment]
@kddejong Any work on this? 
Looks like there is a setting called `cfnLint.ignoreRules`
Any way that can be used?

**Comment by PatMyron** [comment]
merging into the more general issue: https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/68
