### ISSUE TITLE
problem with extension v. 0.10.2; server crashes 5 times

### ISSUE THREAD

**Issue by ustrahlendorf** [aws-cloudformation/aws-cfn-lint-visual-studio-code#75]
Hi there,

got the following message from cfn-lint for VS when working on a CF template in vs:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/uwes/.vscode/extensions/kddejong.vscode-cfn-lint-0.10.2/server/out/server.js:167:28)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 09:36:12] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"enableAutocomplete":true,"validateUsingJsonSchema":false,"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Determined this file is a CloudFormation Template. file:///Users/uwes/EigeneDateien/Projekte/Syneco-SFTP/sftp-server-setup_v4.yml. Found the string AWSTemplateFormatVersion
running............. cfn-lint --format,json,--,"/Users/uwes/EigeneDateien/Projekte/Syneco-SFTP/sftp-server-setup_v4.yml"
/bin/sh: cfn-lint: command not found

child process exited with code 127 and signal null
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/uwes/.vscode/extensions/kddejong.vscode-cfn-lint-0.10.2/server/out/server.js:167:28)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Error - 09:36:12] Connection to server got closed. Server will not be restarted.
```
Any ideas?

**Comment by sviera91** [comment]
Getting the same issue. Right now the cfn-lint extension is just not working. No errors are called out.

**Comment by kddejong** [comment]
@sviera91 and @ustrahlendorf have you installed cfn-lint from pip?  https://pypi.org/project/cfn-lint/

There is a setting to configure the path to cfn-lint if its installed in a location that isn't included by your PATH environment variable.

**Comment by ustrahlendorf** [comment]
Thanks @kddejong, problem fixed, cfn-lint had despaired because of some configuration changes around several python versions :-)
Done re-install through brew, works now for me.

**Comment by kddejong** [comment]
good news.  Thanks @ustrahlendorf

**Comment by sviera91** [comment]
@kddejong  Yeah same here. I just switched laptops and while I installed the extension forgot to install the library through pip. My bad :P Thanks for the help!

**Comment by PatMyron** [comment]
[bundling `cfn-lint` itself](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/60) seems like it would help with these issues as well

**Comment by PatMyron** [comment]
@DScheglov is this [the issue you're running into](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint&ssr=false#review-details)? Does [installing `cfn-lint`](https://github.com/aws-cloudformation/cfn-python-lint/#pip) and making sure that executable is in your [`PATH`](https://en.wikipedia.org/wiki/PATH_(variable)) solve your issue?
